# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

fsd <- function(x) {
    .Call(`_ALSroads_fsd`, x)
}

ffsd <- function(x) {
    .Call(`_ALSroads_ffsd`, x)
}

anisotropic_diffusion <- function(image, iterations, lambda, k) {
    .Call(`_ALSroads_anisotropic_diffusion`, image, iterations, lambda, k)
}

quadtree <- function(las) {
    .Call(`_ALSroads_quadtree`, las)
}

filter_orectangle_with_index <- function(xptr, xmin, ymin, xmax, ymax, angle) {
    .Call(`_ALSroads_filter_orectangle_with_index`, xptr, xmin, ymin, xmax, ymax, angle)
}

